events {
    worker_connections 1024;
}

http {
    # HTTP: редирект на HTTPS и обработка challenge для Certbot
    server {
        listen 80;
        server_name max.mgn-doctor.ru;

        location /.well-known/acme-challenge/ {
            root /var/www/certbot;
            default_type "text/plain";
        }

        location / {
            return 301 https://$host$request_uri;
        }
    }

    # HTTPS: основной сервер
    server {
        listen 443 ssl;
        http2 on; # Исправленный синтаксис для новых версий Nginx
        server_name max.mgn-doctor.ru;

        ssl_certificate /etc/letsencrypt/live/max.mgn-doctor.ru/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/max.mgn-doctor.ru/privkey.pem;

        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers HIGH:!aNULL:!MD5;
        ssl_prefer_server_ciphers on;

        location / {
            proxy_pass http://max-listener:8888;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_connect_timeout       300s;
            proxy_send_timeout          300s;
            proxy_read_timeout          300s;
        }
    }
}